import { getWorld, WORLDS } from '../config/worlds';
import type { AppState, Dialog } from '../core/state';
import { assetUrl } from '../utils/math';
import { icon, logo } from './icons';

const close = `<button class="icon-button dialog-close" data-action="close-dialog" aria-label="Close dialog" autofocus>${icon('close')}</button>`;
const title = (eyebrow: string, heading: string, description = '') => `<div class="dialog-heading"><div class="eyebrow">${eyebrow}</div><h2 id="dialog-title">${heading}</h2>${description ? `<p>${description}</p>` : ''}</div>`;

export function dialogContent(dialog: Exclude<Dialog, null>, state: AppState): string {
  if (dialog === 'atlas') return `${close}${title('THE CELESTIAL ARCHIVE / VOL. 001', 'Find your <em>somewhere.</em>', 'Four faraway worlds. Four reasons to look a little closer.')}
    <div class="atlas-grid">${WORLDS.map(world => {
      const observed = state.observations.some(observation => observation.worldId === world.id);
      return `<button class="atlas-card" data-travel="${world.id}" aria-label="Enter orbit around ${world.name}"><div class="atlas-card-top"><span>${world.index} / ${world.classification}</span><span class="atlas-status ${observed ? 'is-observed' : ''}">${observed ? `${icon('check')} CHARTED` : 'UNCHARTED'}</span></div><div class="atlas-art"><img src="${assetUrl(`assets/worlds/${world.id}.webp`)}" alt="An artist’s impression of ${world.name}" width="220" height="220" /></div><div class="atlas-card-body"><span class="atlas-sector">${world.sector}</span><h3>${world.name}</h3><p>${world.subtitle}</p></div><div class="atlas-card-bottom"><span>${world.distance} <small>LIGHT-YEARS</small></span><span>Enter orbit ${icon('northeast')}</span></div></button>`;
    }).join('')}</div><div class="dialog-footnote">${icon('info')} A speculative atlas. These are imagined worlds, not scientific reconstructions.</div>`;

  if (dialog === 'journal') return `${close}${title('THE PERSONAL EXPLORATION JOURNAL', 'A record of <em>wonder.</em>', 'Small discoveries, worth holding on to.')}
    <div class="journal-progress"><div><span class="journal-progress-number">${state.observations.length}<small> / 04</small></span><span>WORLDS CHARTED</span></div><div class="journal-progress-bars">${WORLDS.map(world => `<span class="${state.observations.some(observation => observation.worldId === world.id) ? 'is-complete' : ''}"></span>`).join('')}</div><span class="journal-journey-label">${state.observations.length === 4 ? 'THE OUTER REACHES, CHARTED' : 'EVERY JOURNEY STARTS WITH CURIOSITY'}</span></div>
    ${state.observations.length ? `<div class="journal-entries">${state.observations.map(observation => {
      const world = getWorld(observation.worldId);
      const recordedAt = new Date(observation.recordedAt);
      return `<article class="journal-entry"><img src="${assetUrl(`assets/worlds/${world.id}.webp`)}" alt="" width="100" height="100" /><div class="journal-entry-body"><div class="journal-entry-title"><h3>${world.name}</h3><span>${icon('check')} OBSERVATION COMPLETE</span></div><p>${world.discovery}</p><div class="journal-facts"><span>${world.radius}</span><span>${world.gravity}</span><span>${world.temperature}</span><span>${world.atmosphere}</span></div><time datetime="${recordedAt.toISOString()}">RECORDED ${recordedAt.toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' })} · ${recordedAt.toLocaleTimeString(undefined, { hour: '2-digit', minute: '2-digit' })}</time></div><button class="icon-button journal-revisit" data-travel="${world.id}" aria-label="Revisit ${world.name}">${icon('northeast')}</button></article>`;
    }).join('')}</div><div class="journal-actions"><button class="secondary-button" data-action="export-log">${icon('download')} Export field notes</button><button class="text-button muted" data-action="confirm-clear">Clear mission log</button></div><div class="clear-confirmation" id="clear-confirmation" hidden><p>Clear all observations? This cannot be undone.</p><div><button class="text-button" data-action="cancel-clear">Keep my discoveries</button><button class="danger-button" data-action="clear-log">Clear observations</button></div></div>` : `<div class="empty-journal"><div class="empty-journal-icon">${icon('compass')}</div><h3>Your journey is still unwritten.</h3><p>Enter orbit and scan a world.<br>What you find will be waiting for you here.</p><button class="primary-button" data-action="journal-explore">Make your first discovery ${icon('arrow')}</button></div>`}
    <div class="dialog-footnote">${icon('book')} Saved on this device. No account, no tracking. Just your corner of the cosmos.</div>`;

  if (dialog === 'settings') return `${close}${title('TUNE YOUR OBSERVATORY', 'Make yourself <em>at home.</em>', 'A little less motion. A little more atmosphere. It’s your universe.')}
    <div class="settings-grid"><section class="settings-section"><h3>${icon('globe')} VISUAL EXPERIENCE</h3>
      <label class="setting-row" for="quality-setting"><span><strong>Rendering quality</strong><small>Auto adapts to your device.</small></span><select id="quality-setting" data-setting="quality">${['auto', 'ultra', 'high', 'medium', 'low'].map(quality => `<option value="${quality}" ${state.settings.quality === quality ? 'selected' : ''}>${quality === 'auto' ? 'Automatic' : quality.charAt(0).toUpperCase() + quality.slice(1)}</option>`).join('')}</select></label>
      <div class="quality-readout" id="quality-readout">${state.renderAvailable ? `WEBGL 2 / ${state.activeQuality.toUpperCase()} QUALITY` : 'STATIC EXPLORATION MODE'}</div>
      ${toggle('reducedMotion', 'Reduced motion', 'Quiet animation and camera transitions.', state.settings.reducedMotion)}
      ${toggle('autoRotate', 'Automatic orbit', 'Let the camera take the scenic route.', state.settings.autoRotate)}
      ${toggle('showOrbits', 'Orbital paths', 'Show the quiet geometry of space.', state.settings.showOrbits)}
    </section><section class="settings-section"><h3>${icon('waves')} SOUND & CONTROL</h3>
      <div class="setting-row"><span><strong>Ambient sound</strong><small>An original, generative soundscape.</small></span><button class="sound-setting-button" id="dialog-sound-button" data-action="sound" aria-pressed="${state.audioEnabled}">${icon(state.audioEnabled ? 'sound' : 'muted')} ${state.audioEnabled ? 'On' : 'Off'}</button></div>
      <label class="range-setting" for="volume-setting"><span><strong>Volume</strong><output id="volume-output">${Math.round(state.settings.volume * 100)}%</output></span><input id="volume-setting" data-setting="volume" type="range" min="0" max="100" value="${Math.round(state.settings.volume * 100)}" /></label>
      <label class="range-setting" for="sensitivity-setting"><span><strong>Orbit sensitivity</strong><output id="sensitivity-output">${state.settings.sensitivity.toFixed(1)}×</output></span><input id="sensitivity-setting" data-setting="sensitivity" type="range" min="3" max="20" value="${Math.round(state.settings.sensitivity * 10)}" /></label>
      <div class="keyboard-guide"><h4>YOUR FLIGHT MANUAL</h4><div><span>Explore / scan</span><span><button class="key-binding" data-rebind="explore" aria-label="Change exploration shortcut">${state.settings.bindings.explore.toUpperCase()}</button><button class="key-binding" data-rebind="scan" aria-label="Change scan shortcut">${state.settings.bindings.scan.toUpperCase()}</button></span></div><div><span>Change world</span><span><kbd>←</kbd><kbd>→</kbd><small>or</small><kbd>1–4</kbd></span></div><div><span>Reset camera / mute</span><span><button class="key-binding" data-rebind="reset" aria-label="Change camera reset shortcut">${state.settings.bindings.reset.toUpperCase()}</button><button class="key-binding" data-rebind="sound" aria-label="Change sound shortcut">${state.settings.bindings.sound.toUpperCase()}</button></span></div><div><span>Pause / return</span><span><kbd>Space</kbd><kbd>Esc</kbd></span></div><p>Click a letter key to reassign it.<br>Drag to orbit. Scroll or pinch to zoom.</p></div>
    </section></div><div class="settings-footer"><span>Preferences are saved automatically on this device.</span><button class="text-button" data-action="reset-settings">Restore defaults ${icon('reset')}</button></div>`;

  return `${close}<div class="about-brand">${logo()}</div>${title('A NOTE FROM THE OBSERVATORY', 'Small worlds.<br><em>Infinite perspective.</em>')}
    <div class="about-copy"><p>There is something quietly extraordinary about looking up. The noise gets smaller. The possibilities get bigger.</p><p>Aether is a small space built around that feeling. An invitation to slow down, follow your curiosity, and spend a little time somewhere you’ve never been.</p><div class="about-principles"><div><span>01</span><strong>Look a little closer.</strong><p>Four imagined worlds, rendered in real-time 3D. Drag, zoom, and find your own point of view.</p></div><div><span>02</span><strong>Leave with a discovery.</strong><p>Enter orbit and scan each world to reveal its story. Your observations stay in your personal mission log.</p></div></div><p class="about-fineprint">An artistic exploration, not an astronomical simulator. World names, coordinates, distances, and scientific readings are fictional. Planetary art combines generated albedo imagery and original procedural textures; the soundscape is synthesized in your browser. Typography: DM Sans and Instrument Serif, licensed under the SIL Open Font License.</p><button class="primary-button" data-action="journal-explore">Let curiosity take over ${icon('arrow')}</button></div>`;
}
function toggle(setting: string, label: string, description: string, checked: boolean): string {
  return `<label class="setting-row toggle-row" for="${setting}-setting"><span><strong>${label}</strong><small>${description}</small></span><span class="toggle"><input id="${setting}-setting" data-setting="${setting}" type="checkbox" ${checked ? 'checked' : ''} /><span class="toggle-track"></span></span></label>`;
}
